### ISSUE TITLE
No longer shown on website?

### ISSUE THREAD

**Issue by isaacs** [joyent/node-in-the-industry#68]
I noticed that these company testimonials are no longer linked from the npmjs.org site, and the CSS on http://www.nodejs.org/industry/ is kinda bizarre.

Is there a reason for this?  It seems weird to stop promoting how popular Node.js is, and it kind of sucks for those of us out here working hard to keep the Node.js ecosystem going strong.

If it's intentional to remove the page, why not remove it all the way?  Why keep it on the site, but unlinked and broken?

**Comment by geek** [comment]
I vote we remove that page for now.

**Comment by tjfontaine** [comment]
We this advent of the Node.js Foundation there will be a lot more work and effort being put into the website. We want to be able to highlight the usage of Node.js in the industry, but right now this mechanism and repository is unmaintained. So I think the right thing to do is to drop it from the website and create a plan for letting users contribute use case stories that can be highlighted on the blog. This can be all supported and maintained by the community with the guidance of the Foundation.

**Comment by isaacs** [comment]
@tjfontaine I think that makes a lot of sense.  Can we put a big fat notice in the README.md that this repo is no more?

**Comment by chorrell** [comment]
I updated the README.md with a warning since we occasionally get pull requests to this repo.

**Comment by chorrell** [comment]
README.md and repo description have been updated.
